// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/new": {
    params: {};
  };
  "/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/api/auth/check-role": {
    params: {};
  };
  "/api/blog/upload-image": {
    params: {};
  };
  "/api/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/api/blog": {
    params: {};
  };
  "/api/images/*": {
    params: {
      "*": string;
    };
  };
  "/internships": {
    params: {};
  };
  "/internships/new": {
    params: {};
  };
  "/internships/:id": {
    params: {
      "id": string;
    };
  };
  "/internships/:id/applications": {
    params: {
      "id": string;
    };
  };
  "/api/internships": {
    params: {};
  };
  "/api/internships/:id": {
    params: {
      "id": string;
    };
  };
  "/api/internships/:id/applications": {
    params: {
      "id": string;
    };
  };
  "/api/internships/applications/:id": {
    params: {
      "id": string;
    };
  };
  "/api/internships/applications/:id/download": {
    params: {
      "id": string;
    };
  };
  "/api/internships/applications/:id/view": {
    params: {
      "id": string;
    };
  };
  "/api/internships/applications/forward": {
    params: {};
  };
  "/api/companies": {
    params: {};
  };
  "/api/companies/:id": {
    params: {
      "id": string;
    };
  };
  "/api/companies/:id/partner-users": {
    params: {
      "id": string;
    };
  };
  "/companies": {
    params: {};
  };
  "/companies/new": {
    params: {};
  };
  "/companies/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/blog" | "/blog/new" | "/blog/:id" | "/api/auth/check-role" | "/api/blog/upload-image" | "/api/blog/:id" | "/api/blog" | "/api/images/*" | "/internships" | "/internships/new" | "/internships/:id" | "/internships/:id/applications" | "/api/internships" | "/api/internships/:id" | "/api/internships/:id/applications" | "/api/internships/applications/:id" | "/api/internships/applications/:id/download" | "/api/internships/applications/:id/view" | "/api/internships/applications/forward" | "/api/companies" | "/api/companies/:id" | "/api/companies/:id/partner-users" | "/companies" | "/companies/new" | "/companies/:id";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/blog/index.tsx": {
    id: "routes/blog/index";
    page: "/blog";
  };
  "routes/blog/new.tsx": {
    id: "routes/blog/new";
    page: "/blog/new";
  };
  "routes/blog/$id.tsx": {
    id: "routes/blog/$id";
    page: "/blog/:id";
  };
  "routes/api.auth.check-role.tsx": {
    id: "routes/api.auth.check-role";
    page: "/api/auth/check-role";
  };
  "routes/api/blog/upload-image.tsx": {
    id: "routes/api/blog/upload-image";
    page: "/api/blog/upload-image";
  };
  "routes/api/blog/$id.tsx": {
    id: "routes/api/blog/$id";
    page: "/api/blog/:id";
  };
  "routes/api/blog/route.tsx": {
    id: "routes/api/blog/route";
    page: "/api/blog";
  };
  "routes/api/images/$.tsx": {
    id: "routes/api/images/$";
    page: "/api/images/*";
  };
  "routes/internships/index.tsx": {
    id: "routes/internships/index";
    page: "/internships";
  };
  "routes/internships/new.tsx": {
    id: "routes/internships/new";
    page: "/internships/new";
  };
  "routes/internships/$id.tsx": {
    id: "routes/internships/$id";
    page: "/internships/:id";
  };
  "routes/internships/$id/applications.tsx": {
    id: "routes/internships/$id/applications";
    page: "/internships/:id/applications";
  };
  "routes/api/internships/route.tsx": {
    id: "routes/api/internships/route";
    page: "/api/internships";
  };
  "routes/api/internships/$id.tsx": {
    id: "routes/api/internships/$id";
    page: "/api/internships/:id";
  };
  "routes/api/internships/$id/applications.tsx": {
    id: "routes/api/internships/$id/applications";
    page: "/api/internships/:id/applications";
  };
  "routes/api/internships/applications/$id.tsx": {
    id: "routes/api/internships/applications/$id";
    page: "/api/internships/applications/:id";
  };
  "routes/api/internships/applications/$id/download.tsx": {
    id: "routes/api/internships/applications/$id/download";
    page: "/api/internships/applications/:id/download";
  };
  "routes/api/internships/applications/$id/view.tsx": {
    id: "routes/api/internships/applications/$id/view";
    page: "/api/internships/applications/:id/view";
  };
  "routes/api/internships/applications/forward.tsx": {
    id: "routes/api/internships/applications/forward";
    page: "/api/internships/applications/forward";
  };
  "routes/api/companies/route.tsx": {
    id: "routes/api/companies/route";
    page: "/api/companies";
  };
  "routes/api/companies/$id.tsx": {
    id: "routes/api/companies/$id";
    page: "/api/companies/:id";
  };
  "routes/api/companies/$id/partner-users.tsx": {
    id: "routes/api/companies/$id/partner-users";
    page: "/api/companies/:id/partner-users";
  };
  "routes/companies/index.tsx": {
    id: "routes/companies/index";
    page: "/companies";
  };
  "routes/companies/new.tsx": {
    id: "routes/companies/new";
    page: "/companies/new";
  };
  "routes/companies/$id.tsx": {
    id: "routes/companies/$id";
    page: "/companies/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/blog/index": typeof import("./app/routes/blog/index.tsx");
  "routes/blog/new": typeof import("./app/routes/blog/new.tsx");
  "routes/blog/$id": typeof import("./app/routes/blog/$id.tsx");
  "routes/api.auth.check-role": typeof import("./app/routes/api.auth.check-role.tsx");
  "routes/api/blog/upload-image": typeof import("./app/routes/api/blog/upload-image.tsx");
  "routes/api/blog/$id": typeof import("./app/routes/api/blog/$id.tsx");
  "routes/api/blog/route": typeof import("./app/routes/api/blog/route.tsx");
  "routes/api/images/$": typeof import("./app/routes/api/images/$.tsx");
  "routes/internships/index": typeof import("./app/routes/internships/index.tsx");
  "routes/internships/new": typeof import("./app/routes/internships/new.tsx");
  "routes/internships/$id": typeof import("./app/routes/internships/$id.tsx");
  "routes/internships/$id/applications": typeof import("./app/routes/internships/$id/applications.tsx");
  "routes/api/internships/route": typeof import("./app/routes/api/internships/route.tsx");
  "routes/api/internships/$id": typeof import("./app/routes/api/internships/$id.tsx");
  "routes/api/internships/$id/applications": typeof import("./app/routes/api/internships/$id/applications.tsx");
  "routes/api/internships/applications/$id": typeof import("./app/routes/api/internships/applications/$id.tsx");
  "routes/api/internships/applications/$id/download": typeof import("./app/routes/api/internships/applications/$id/download.tsx");
  "routes/api/internships/applications/$id/view": typeof import("./app/routes/api/internships/applications/$id/view.tsx");
  "routes/api/internships/applications/forward": typeof import("./app/routes/api/internships/applications/forward.tsx");
  "routes/api/companies/route": typeof import("./app/routes/api/companies/route.tsx");
  "routes/api/companies/$id": typeof import("./app/routes/api/companies/$id.tsx");
  "routes/api/companies/$id/partner-users": typeof import("./app/routes/api/companies/$id/partner-users.tsx");
  "routes/companies/index": typeof import("./app/routes/companies/index.tsx");
  "routes/companies/new": typeof import("./app/routes/companies/new.tsx");
  "routes/companies/$id": typeof import("./app/routes/companies/$id.tsx");
};